version: "2"
services:
  stun-server:
    container_name: mileworks-stun
    build: ./stun
    ports:
      - "1111:1111"

  turn-server:
    container_name: coturn
    build: ./coturn
    ports:
      - "3478:3478"
    depends_on:
      - "mileworks-stun"

  kurento-media-server:
    container_name: kms
    build: ./kurento
    ports:
      - "8888:8888"
    depends_on:
      - "coturn"
    volumes:
      - ./kurento/WebRtcEndpoint.conf.ini:/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini

  tomcat-server:
    container_name: mileworks-signal-server
    build: ./tomcat
    depends_on:
      - "kms"
    ports:
      - "8448:8080"
      - "8443:8443"