version: "2"
services:
  stun-server:
    container_name: mileworks-stun
    build: ./stun
    expose:
      - "1111"

  turn-server:
    container_name: mileworks-turn
    image: steppechange/docker-coturn
    #指定本地文件
    volumes: 
      - ./coturn/turnserver.conf:/opt/coturn/etc/turnserver.conf
    expose:
      - "3478"

  kurento-media-server:
    container_name: kms
    image: kurento/kurento-media-server
    volumes: 
      - ./kurento/WebRtcEndpoint.conf.ini:/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
    expose:
      - "8888"

  jweb-singnal-server:
    container_name: mileworks-signal-server
    build: ./webrtc
    expose:
      - "8443"
