version: "2"
services:
  stun-server:
    container_name: mileworks-stun
    build: ./stun
    ports:
      - "1111:1111"

  turn-server:
    container_name: mileworks-turn
    build: ./coturn
    ports:
      - "3478:3478"

  kurento-media-server:
    container_name: mileworks-kms
    build: ./kurento
    ports:
      - "8888:8888"

  tomcat-server:
    container_name: mileworks-signal-server
    build: ./tomcat
    ports:
      - "8448:8080"
      - "8443:8443"