version: "1.0"
services:
  kurento-media-server:
    container_name: kms
    image: kurento/kurento-media-server
    expose:
      - "8888:8888"
  
  stun-server:
    container_name: mileworks-stun
    build: ./stun/Dockefile
    ports:
      - "1111:1111"

  jweb-singnal-server:
    container_name: mileworks-signal-server
    build: ./webrtc/Dockefile
    ports:
      - "8443:8443"

  turn-server:
    container_name: webrtc-turn-sever
    image: kurento/kurento-media-server
    expose:
      - "6379"

  vertx-todo-backend:
    depends_on:
      - redis
    container_name: vertx-todo-backend_service
    build: .
    links:
      - redis
    ports:
      - "8082:8082"
